-- Migration 005_membership_audit_log.sql
CREATE TABLE IF NOT EXISTS public.membership_audit_log (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action          text         NOT NULL,
  performed_by    text         NOT NULL,
  target_user_id  uuid         REFERENCES public.profiles(id) ON DELETE SET NULL,
  metadata        jsonb,
  created_at      timestamptz  NOT NULL DEFAULT now()
);

ALTER TABLE public.membership_audit_log ENABLE ROW LEVEL SECURITY;

-- Append-only: no application-layer updates or deletes
DO $$ BEGIN
  CREATE POLICY "audit_log: no update"
    ON public.membership_audit_log FOR UPDATE
    USING (false);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "audit_log: no delete"
    ON public.membership_audit_log FOR DELETE
    USING (false);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Service role can insert and select
DO $$ BEGIN
  CREATE POLICY "audit_log: service role insert select"
    ON public.membership_audit_log FOR ALL
    USING (auth.role() = 'service_role');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_audit_log_created_at
  ON public.membership_audit_log (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_log_target_user
  ON public.membership_audit_log (target_user_id)
  WHERE target_user_id IS NOT NULL;
