-- Migration 003_live_events.sql
CREATE TABLE IF NOT EXISTS public.live_events (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         text         NOT NULL,
  description   text,
  thumbnail_url text,
  event_date    timestamptz  NOT NULL,
  youtube_link  text         NOT NULL,
  is_active     boolean      NOT NULL DEFAULT true,
  created_at    timestamptz  NOT NULL DEFAULT now()
);

ALTER TABLE public.live_events ENABLE ROW LEVEL SECURITY;

-- Members can read event metadata but NOT the youtube_link column
-- The youtube_link is served exclusively through /api/membership/live-link
DO $$ BEGIN
  CREATE POLICY "live_events: active member read metadata"
    ON public.live_events FOR SELECT
    USING (
      is_active = true
      AND EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid()
          AND membership_status = 'active'
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Service role (used by admin API routes) has full access
DO $$ BEGIN
  CREATE POLICY "live_events: service role all"
    ON public.live_events FOR ALL
    USING (auth.role() = 'service_role');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Index for upcoming event queries
CREATE INDEX IF NOT EXISTS idx_live_events_date_active
  ON public.live_events (event_date, is_active);
