-- Migration 004_admin_settings.sql
CREATE TABLE IF NOT EXISTS public.admin_settings (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key        text         NOT NULL UNIQUE,
  value      text,
  updated_at timestamptz  NOT NULL DEFAULT now()
);

ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;

-- Public read (used by /api/membership/whatsapp-number — no auth required)
DO $$ BEGIN
  CREATE POLICY "admin_settings: public read"
    ON public.admin_settings FOR SELECT
    TO public USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Only service role may write (admin API routes use service key)
DO $$ BEGIN
  CREATE POLICY "admin_settings: service role write"
    ON public.admin_settings FOR ALL
    USING (auth.role() = 'service_role');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Seed default WhatsApp placeholder (safe to re-run)
INSERT INTO public.admin_settings (key, value)
VALUES ('whatsapp_number', '')
ON CONFLICT (key) DO NOTHING;
