-- ============================================================
-- AstroGenZ Membership Coupons
-- Run in Supabase SQL Editor.
-- ============================================================

-- 1. membership_coupons
create table if not exists public.membership_coupons (
  id               bigint generated by default as identity primary key,
  code             text not null unique,
  discount_type    text not null check (discount_type in ('percent', 'fixed')),
  discount_value   numeric(10,2) not null,
  max_uses         integer,          -- null = unlimited
  used_count       integer not null default 0,
  expires_at       timestamptz,      -- null = never expires
  is_active        boolean not null default true,
  created_at       timestamptz default now()
);

alter table public.membership_coupons enable row level security;

-- Anyone can read active coupons (needed to validate on client for UX)
-- Real validation happens server-side
do $$ begin
  create policy "membership_coupons: public read active"
    on public.membership_coupons for select
    to public using (is_active = true);
exception when duplicate_object then null; end $$;

-- Full access for management
do $$ begin
  create policy "membership_coupons: anon all"
    on public.membership_coupons for all
    to public using (true) with check (true);
exception when duplicate_object then null; end $$;

-- 2. membership_coupon_uses — track which user used which coupon
create table if not exists public.membership_coupon_uses (
  id          bigint generated by default as identity primary key,
  coupon_id   bigint not null references public.membership_coupons(id),
  user_id     uuid   not null references public.profiles(id),
  used_at     timestamptz default now(),
  unique (coupon_id, user_id)   -- one use per user per coupon
);

alter table public.membership_coupon_uses enable row level security;

do $$ begin
  create policy "coupon_uses: anon all"
    on public.membership_coupon_uses for all
    to public using (true) with check (true);
exception when duplicate_object then null; end $$;
