-- ============================================================
-- Coupons table + service discount_percent column
-- Run this once in the Supabase SQL editor.
-- ============================================================

-- 1. Add discount_percent column to services table
--    (0 = no discount, 10 = 10% off the service price)
alter table public.services
  add column if not exists discount_percent numeric(5, 2) not null default 0;

-- 2. Create coupons table
--    Admin creates coupon codes here; users enter them at checkout
--    for an additional % discount on top of any service-level discount.
create table if not exists public.coupons (
  id         bigint generated by default as identity primary key,
  code       text not null unique,        -- uppercase, e.g. SAVE20
  discount_percent numeric(5, 2) not null default 0, -- e.g. 15 for 15% off
  active     boolean not null default true,
  description text,                       -- shown to user when code is applied
  created_at timestamptz default now()
);

-- 3. Row-level security
alter table public.coupons enable row level security;

-- Allow anyone (anon key) to read coupons so the booking form can validate codes
create policy "public read coupons"
on public.coupons
for select
to public
using (true);

-- Allow anon inserts/updates so the admin panel (anon key) can manage coupons
create policy "public insert coupons"
on public.coupons
for insert
to public
with check (true);

create policy "public update coupons"
on public.coupons
for update
to public
using (true)
with check (true);

create policy "public delete coupons"
on public.coupons
for delete
to public
using (true);

-- ============================================================
-- Optional sample data — remove or adjust before production
-- ============================================================
insert into public.coupons (code, discount_percent, active, description)
values
  ('WELCOME10', 10, true, 'Welcome offer — 10% extra off your first booking'),
  ('FESTIVE20', 20, true, 'Festive season special — 20% additional discount')
on conflict (code) do nothing;
