create table if not exists public.payment_proofs (
  id bigint generated by default as identity primary key,
  customer_name text,
  email text,
  phone_number text,
  service_name text,
  amount numeric,
  payment_screenshot_url text,
  notes text,
  status text default 'pending',
  created_at timestamptz default now()
);

alter table public.payment_proofs enable row level security;

create policy "public insert payment proofs"
on public.payment_proofs
for insert
to public
with check (true);

create policy "public read payment proofs"
on public.payment_proofs
for select
to public
using (true);

create policy "public update payment proofs"
on public.payment_proofs
for update
to public
using (true)
with check (true);
