-- ============================================================
-- AstroGenZ Membership System — Database Setup
-- Run this once in the Supabase SQL editor.
-- Does NOT modify any existing tables.
-- Uses IF NOT EXISTS and DROP IF EXISTS to be safe to re-run.
-- ============================================================

-- 1. profiles — one row per authenticated user
create table if not exists public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  email        text,
  full_name    text,
  avatar_url   text,
  premium      boolean not null default false,
  created_at   timestamptz default now()
);

alter table public.profiles enable row level security;

-- Users can read their own profile
do $$ begin
  create policy "profiles: own read"
    on public.profiles for select
    using (auth.uid() = id);
exception when duplicate_object then null;
end $$;

-- Users can update their own non-premium fields
do $$ begin
  create policy "profiles: own update"
    on public.profiles for update
    using (auth.uid() = id)
    with check (auth.uid() = id);
exception when duplicate_object then null;
end $$;

-- Service role can do everything (admin approval)
do $$ begin
  create policy "profiles: service role all"
    on public.profiles for all
    using (auth.role() = 'service_role');
exception when duplicate_object then null;
end $$;

-- Auto-create profile on sign up
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ──────────────────────────────────────────────────────────
-- 2. membership_settings — single row admin controls
-- ──────────────────────────────────────────────────────────
create table if not exists public.membership_settings (
  id                 bigint generated by default as identity primary key,
  membership_price   numeric(10,2) not null default 999,
  membership_enabled boolean not null default true,
  created_at         timestamptz default now(),
  updated_at         timestamptz default now()
);

alter table public.membership_settings enable row level security;

do $$ begin
  create policy "membership_settings: public read"
    on public.membership_settings for select
    to public using (true);
exception when duplicate_object then null;
end $$;

do $$ begin
  create policy "membership_settings: service role write"
    on public.membership_settings for all
    using (auth.role() = 'service_role');
exception when duplicate_object then null;
end $$;

-- Insert default record only if empty
insert into public.membership_settings (membership_price, membership_enabled)
select 999, true
where not exists (select 1 from public.membership_settings);

-- ──────────────────────────────────────────────────────────
-- 3. membership_purchases
-- ──────────────────────────────────────────────────────────
create table if not exists public.membership_purchases (
  id             bigint generated by default as identity primary key,
  user_id        uuid references public.profiles(id) on delete cascade,
  amount_paid    numeric(10,2),
  payment_id     text,
  payment_proof  text,
  status         text not null default 'pending'
                 check (status in ('pending','approved','rejected')),
  approved_by    text,
  approved_at    timestamptz,
  created_at     timestamptz default now()
);

alter table public.membership_purchases enable row level security;

do $$ begin
  create policy "purchases: own insert"
    on public.membership_purchases for insert
    with check (auth.uid() = user_id);
exception when duplicate_object then null;
end $$;

do $$ begin
  create policy "purchases: own read"
    on public.membership_purchases for select
    using (auth.uid() = user_id);
exception when duplicate_object then null;
end $$;

do $$ begin
  create policy "purchases: service role all"
    on public.membership_purchases for all
    using (auth.role() = 'service_role');
exception when duplicate_object then null;
end $$;

-- ──────────────────────────────────────────────────────────
-- 4. premium_videos
-- ──────────────────────────────────────────────────────────
create table if not exists public.premium_videos (
  id            bigint generated by default as identity primary key,
  title         text not null,
  description   text,
  video_url     text not null,
  thumbnail_url text,
  category      text default 'General',
  sort_order    integer default 0,
  is_active     boolean not null default true,
  created_at    timestamptz default now()
);

alter table public.premium_videos enable row level security;

do $$ begin
  create policy "premium_videos: premium read"
    on public.premium_videos for select
    using (
      exists (
        select 1 from public.profiles
        where id = auth.uid() and premium = true
      )
    );
exception when duplicate_object then null;
end $$;

do $$ begin
  create policy "premium_videos: service role all"
    on public.premium_videos for all
    using (auth.role() = 'service_role');
exception when duplicate_object then null;
end $$;

-- ──────────────────────────────────────────────────────────
-- Helper functions
-- ──────────────────────────────────────────────────────────
create or replace function public.approve_membership(
  p_purchase_id bigint,
  p_admin_name  text default 'admin'
)
returns void language plpgsql security definer as $$
declare
  v_user_id uuid;
begin
  select user_id into v_user_id
  from public.membership_purchases
  where id = p_purchase_id;

  if v_user_id is null then
    raise exception 'Purchase not found';
  end if;

  update public.membership_purchases
  set status = 'approved',
      approved_by = p_admin_name,
      approved_at = now()
  where id = p_purchase_id;

  update public.profiles
  set premium = true
  where id = v_user_id;
end;
$$;

create or replace function public.reject_membership(
  p_purchase_id bigint,
  p_admin_name  text default 'admin'
)
returns void language plpgsql security definer as $$
begin
  update public.membership_purchases
  set status = 'rejected',
      approved_by = p_admin_name,
      approved_at = now()
  where id = p_purchase_id;
end;
$$;
