create table if not exists public.payment_proofs (
  id bigint generated by default as identity primary key,
  customer_name text,
  email text,
  phone_number text,
  service_name text,
  amount numeric,
  original_amount numeric,
  coupon_code text,
  coupon_discount_percent numeric(5,2),
  payment_screenshot_url text,
  notes text,
  status text default 'pending',
  created_at timestamptz default now()
);

alter table public.payment_proofs enable row level security;

create policy "public insert payment proofs"
on public.payment_proofs
for insert
to public
with check (true);

create policy "public read payment proofs"
on public.payment_proofs
for select
to public
using (true);

create policy "public update payment proofs"
on public.payment_proofs
for update
to public
using (true)
with check (true);

-- ============================================================
-- Migration: add coupon tracking columns to existing table
-- Run this if you already created payment_proofs without them.
-- ============================================================
alter table public.payment_proofs
  add column if not exists original_amount numeric,
  add column if not exists coupon_code text,
  add column if not exists coupon_discount_percent numeric(5,2);

-- ============================================================
-- Migration: add Razorpay columns to existing payment_proofs
-- Run this if you already created the table without them.
-- ============================================================
alter table public.payment_proofs
  add column if not exists razorpay_order_id text,
  add column if not exists razorpay_payment_id text;
